In [18]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
a=np.array(80)
print(a)
print(type(a))
print(a.ndim)


80
<class 'numpy.ndarray'>
0


In [8]:
b=np.array([1,2,3,4])
print(b)
print(type(b))
print(b.ndim)


[1 2 3 4]
<class 'numpy.ndarray'>
1


In [9]:
c=np.array([[1,2,3,4],[5,6,7,8]])
print(c)
print(type(c))
print(c.ndim)

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
2


In [11]:
d=np.array([[[1,2,3,4],[5,6,7,8],[1,2,3,4],[5,6,7,8]]])
print(d)
print(type(d))
print(d.ndim)


[[[1 2 3 4]
  [5 6 7 8]
  [1 2 3 4]
  [5 6 7 8]]]
<class 'numpy.ndarray'>
3


In [12]:
x=np.array([3,5.6,"python",7+9j,True,False])
print(x)
print(type(x))
print(x.ndim)


['3' '5.6' 'python' '(7+9j)' 'True' 'False']
<class 'numpy.ndarray'>
1


In [13]:
a=[1,2,3,4,5]
b=[5,6,7,8,9]
print(a+b)

[1, 2, 3, 4, 5, 5, 6, 7, 8, 9]


In [14]:
a=np.array([1,2,3,4,5])
b=np.array([5,6,7,8,9])
print(a+b)

[ 6  8 10 12 14]


In [15]:
c=np.sum(a)
print(c)

d=np.sum(b)
print(d)

15
35


In [17]:
x=np.mean(a)
print(x)

y=np.mean(b)
print(y)

3.0
7.0
